In [1]:
import numpy as np

In [2]:
# n=1
# st=18
# last=st*n-1
# print('last=\n',last)
# val=np.arange(start=1, stop=last, step=n)
# print(val)
# newarr = val.reshape(4, 4)
# print(newarr)

In [4]:
newarr = np.array([[1, 2, 3,4], [ 5, 6, 7,8], [9, 10,11,12], [13,14,15,16]])
img=newarr
print(img)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [5]:
# output=np.convolve(img)
# print(output)

In [6]:
from scipy import signal
kernel=np.array([[1, 1, 1], [1, 1, 1], [1, 1, 1]])
print('kernel=\n',kernel)
print('img=\n',img)

kernel=
 [[1 1 1]
 [1 1 1]
 [1 1 1]]
img=
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [7]:
# Convolve two 2-dimensional arrays.
# Convolve in1 and in2 with output size determined by mode, and boundary conditions determined by boundary and fillvalue.
# https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.convolve2d.html

# output = signal.convolve2d(img, kernel, boundary='symm', mode='same')
output = signal.convolve2d(img, kernel,fillvalue=0)
print('output=\n',output)

output=
 [[ 1  3  6  9  7  4]
 [ 6 14 24 30 22 12]
 [15 33 54 63 45 24]
 [27 57 90 99 69 36]
 [22 46 72 78 54 28]
 [13 27 42 45 31 16]]


In [8]:
# pad input arrays with fillvalue. (default)
output = signal.convolve2d(img, kernel, boundary='fill', mode='same',fillvalue=0)
print('output=\n',output)

output=
 [[14 24 30 22]
 [33 54 63 45]
 [57 90 99 69]
 [46 72 78 54]]


In [9]:
# output = signal.convolve2d(img, kernel, boundary='wrap', mode='same')
# print('output=\n',output)

In [10]:
# # pad input arrays with fillvalue. (default)
# output = signal.convolve2d(img, kernel, boundary='fill', fillvalue=0)
# print('output=\n',output)